"""Gymboard - Web dashboard for Gymkhana RL training data visualization.

A lightweight monitoring tool for viewing trajectories, rollouts, and training data
generated by Gymkhana environments.
"""

__version__ = "0.1.0"

from .app import app

__all__ = ["app"]
